apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheque-verification-frontend
  labels:
    app.kubernetes.io/name: cheque-verification-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cheque-verification-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cheque-verification-frontend
    spec:
      imagePullSecrets:
        - name: github-docker-registry
      containers:
        - name: cheque-verification-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3001
              name: health
          env:
            - name: BACKEND_URL
              value: {{ .Values.config.BACKEND_URL | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.LOG_LEVEL | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always