{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cheque-verification-frontend
  labels:
    app.kubernetes.io/name: cheque-verification-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cheque-verification-frontend
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
