apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cheque-verification-frontend
  labels:
    app.kubernetes.io/name: cheque-verification-frontend
  {{- if .Values.route.annotations }}
  annotations:
    {{- toYaml .Values.route.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: cheque-verification-frontend
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
