{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cheque-verification-frontend
  labels:
    app.kubernetes.io/name: cheque-verification-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: cheque-verification-frontend
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
{{- end }}