{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cheque-verification-backend
  labels:
    app.kubernetes.io/name: cheque-verification-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cheque-verification-backend
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
